# Generated by Django 5.0.6 on 2024-09-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='user',
        ),
    ]
